### ISSUE TITLE
Ux improvements for commit list

### ISSUE THREAD

**Issue by colinjfw** [deliverybot/deliverybot#26]
Currently the UX around the commit list, which currently looks like the below shot needs a bit of work. The suggested change is below. Let me know what you think and if this adds clarity.

Issues:
- Too many long popovers.
- Button implies that it should do something.
- Misunderstanding of the target filter.
- What's a CI check vs a deployment check?

##### Current

<img width="777" alt="Screen Shot 2020-01-15 at 8 45 47 AM" src="https://user-images.githubusercontent.com/10747761/72453138-78763180-3773-11ea-9fd7-d8dfd40f9add.png">

##### Suggested change

Changing up a row of commits to look like:
<img width="867" alt="Screen Shot 2020-01-15 at 8 40 56 AM" src="https://user-images.githubusercontent.com/10747761/72452658-c8082d80-3772-11ea-8e18-a7ddad960fa3.png">

And when expanded:
<img width="873" alt="Screen Shot 2020-01-15 at 8 44 57 AM" src="https://user-images.githubusercontent.com/10747761/72453052-5ed4ea00-3773-11ea-9eb9-94789ad1e204.png">

**Comment by colinjfw** [comment]
@jbergstoem what do you think of the suggestions here?

**Comment by jbergstroem** [comment]
> @jbergstroem what do you think of the suggestions here?

Sorry, missed this. 

Clear improvement. I would change the "about a month ago" to exact date though.
Also, if that commit is tagged, I would decorate that as well.

**Comment by tmayr** [comment]
Hey Colin!, @jbergstroem just shared this with me, so I thought i'd add my two cents,


I'd add where the last deployment target was to the title.

"The last deployment to Production has succeeded" and maybe separate Checks from Deployments boxes to make it more clear that they're different things

**Comment by tmayr** [comment]
Also, this is labeled as Help Wanted, I'd love to help somehow if needed!

**Comment by colinjfw** [comment]
@tmayr thanks for the feedback ;). Those are great points, at the moment the code is closed source so I can't easily get someone to help on it. I'm slowly working on trying to get it open source but maybe I'll prioritize that a little higher so I can get some good feedback on this.

**Comment by colinjfw** [comment]
Released.
