### ISSUE TITLE
404 error when changing to a branch with / in its name

### ISSUE THREAD

**Issue by imella** [deliverybot/deliverybot#29]
In the deliverybot UI if I change to a branch with a `/` in its name it throws a 404 error (ex: `feat/new-amazing-feature`)

<img width="908" alt="Screen Shot 2020-01-28 at 16 15 21" src="https://user-images.githubusercontent.com/741631/73297450-5e643680-41ea-11ea-84ad-c48c784d6403.png">

Selecting a branch with `/`

<img width="1142" alt="Screen Shot 2020-01-28 at 16 15 49" src="https://user-images.githubusercontent.com/741631/73297561-8eabd500-41ea-11ea-9284-ff070a648ff8.png">

404 error

<img width="1680" alt="Screen Shot 2020-01-28 at 16 16 24" src="https://user-images.githubusercontent.com/741631/73297694-ca469f00-41ea-11ea-98c8-4cf0a4e0d6c8.png">

**Comment by colinjfw** [comment]
<img width="420" alt="Screen Shot 2020-02-20 at 7 11 07 AM" src="https://user-images.githubusercontent.com/10747761/74947792-3cf10780-53b0-11ea-8c1e-d43e85db776e.png">

@imella I believe this is all good now but feel free to re-open if it's still an issue.
